version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "8000:3000"
    environment:
      - NODE_ENV=development